export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const ACTIVE_USERS_COUNT = 'ACTIVE_USERS_COUNT'

export const SEND_MESSAGE = 'SEND_MESSAGE'

export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
